import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import { Footer } from "./components/footer/Footer";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <div className="container">
          <div className="wrapper">
            <Providers>
              <Navbar />
              {children}
            </Providers>
            {/* <Footer /> */}
          </div>
        </div>
      </body>
    </html>
  );
}
